id: P01011D30
initial_creation_type: input
source_metadata:
  Title: ''
  Editor: Sāṅkṛtyāyana, Rāhula
  Publisher: Central Institute of Higher Tibetan Studies,
  Place of Publication: Sarnath
  Year: '2007'
  वादन्यायटीका:
    Text Version: Devanagari
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T17:00:08.018427'
last_modified_at: '2022-03-08T17:00:08.018435'
